### ISSUE TITLE
[DOCS] Add contribution guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Botchain#9]
### Description

I can work on this if required.

**Comment by thevinitgupta** [comment]
I would love to work on this.

**Comment by Pradumnasaraf** [comment]
> I would love to work on this.

Yes, go ahead. This should be the pattern and content. Change the link and tech accordingly.

https://github.com/Pradumnasaraf/Post-My-Message/blob/main/CONTRIBUTING.md
